# Site settings
title: JirmShin
description: 'JrmShin`s Blog'
url: 'http://JirmShin.github.io'
baseurl: ''
google_analytics: 'UA-290650173-2'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'JirmShin'
  email: sundory1@naver.com
  # twitter_username: Moneydory
  # facebook_username: JirmShin
  # github_username: JirmShin
  # linkedin_username:  JirmShin

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
